Book_Store/Controllers/AuthorController.cs
using BLL.Dtos;
using BLL.Interfaces;
using BLL.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Book_Store.Controllers
{
    [Authorize(Roles = "BasicUser")]
    public class AuthorController : Controller
    {
        private readonly IAutherService _AuthorService;

        public AuthorController(IAutherService authorService)
        {
            _AuthorService = authorService;
        }

        public async Task<IActionResult> Index()
        {
            var Result = await _AuthorService.GetAuthorsAsync();
            return View(Result);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(AuthorDto author)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var Result = await _AuthorService.AddAsync(author);
                    return RedirectToAction("Index");
                }
                else
                    throw new Exception("Data Is Not Valid");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(author);
            }
           
        }

        public async Task<IActionResult> Update(int id)
        {
            var Author = await _AuthorService.GetAuthorByIdAsync(id);
            
            return View(Author);
        }
        [HttpPost]
        public async Task<IActionResult> Update(AuthorDto author)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _AuthorService.UpdateAsync(author);
                    return RedirectToAction("Index");
                }
                else
                    throw new Exception("Data Is Not Valid");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(author);
            }


        }




        public async Task<IActionResult> Delete(int id)
        {
            var Author = await _AuthorService.GetAuthorByIdAsync(id);
           
            return View(Author);


        }
        [HttpPost]
        public async Task<IActionResult> Delete(AuthorDto author)
        {
            await _AuthorService.DeleteAsync(author.Id);
            return RedirectToAction("Index");

        }
    }
}

Book_Store/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace Book_Store.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
      
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;  
        }
        public async Task<IActionResult> Index()
        {
            var Roles = await _roleManager.Roles.ToListAsync();
           
            return View(Roles);
        }
        public async Task<IActionResult> Create()
        {
           
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            try
            { 
                if(role==null)
                    throw new Exception("Please Enter Role Name");
                else
                {
                    var result = await _roleManager.CreateAsync(role);
                    if (result.Succeeded)
                        return RedirectToAction("Index");
                    else
                    {
                        throw new Exception("Cannot Create This Role");
                    }
                }

            }catch (Exception ex)
            {
                throw new Exception(ex.Message);
                return View(role);
            }
           
        }
    }
}

Book_Store/Views/Role/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>
@model Microsoft.AspNetCore.Identity.IdentityRole;


<form asp-controller="Role" asp-action="Create" method="post">
    <div asp-validation-summary="All">
    </div>
    <div class="form-group">
        <label> Role Name</label>
        <input type="text" class="form-control" placeholder="Enter Name" asp-for="Name">
        <span asp-validation-for="Name" class="text-danger"></span>

    </div>




    <button class="btn btn-info" type="submit">Add</button>

</form>



@section MicroSoftValidation {

    <script src="~/plugins//jquery-validation//jquery.validate.js"> </script>
    <script src="~/plugins/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Book_Store/Views/Role/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>;

<h2>Index</h2>
<div class="col-md-3">
    <a class="w-100" asp-controller="Role" asp-action="Create"><button class="btn btn-primary w-100">Add</button></a>
</div>

<table class="table">

    <tbody>


        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col"># ID</th>

                    <th scope="col">Name</th>


                    <th scope="col">Update</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.Id</th>
                        <td>@item.Name</td>
                        


                        <td>  <a asp-route-Id="@item.Id" asp-controller="Author" asp-action="Update"> <button class="btn btn-info">Update</button> </a></td>
                        <td> <a asp-route-Id="@item.Id" asp-controller="Author" asp-action="Delete"> <button class="btn btn-danger">Delete</button> </a></td>
                    </tr>
                }


            </tbody>
        </table>



    </tbody>
</table>