Book_Store/Controllers/AuthorsBooksController.cs
using BLL.Dtos;
using BLL.interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Book_Store.Controllers
{
    public class AuthorsBooksController : Controller
    {
        private readonly IAuthorsBooksService _authorsBooksService;
        public AuthorsBooksController(IAuthorsBooksService authorsBooksService)
        {
              _authorsBooksService = authorsBooksService;
        }
        
        public async Task<IActionResult> Index()
        {
            var Result= await _authorsBooksService.GetAuthorsBooksAsync();
            return View(Result);
        }
        public async Task<IActionResult> Create()
        {
           
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(AuthorsBooksDto authorBook)
        {
            try
            {
                if(ModelState.IsValid)
                {
                   await _authorsBooksService.AddAsync(authorBook);
                    return RedirectToAction("Index");
                    
                }
                else
                {
                    throw new Exception("Data Is Not Valid");
                }

            }catch( Exception ex) 
            {
                ModelState.AddModelError("", ex.Message);
                return View(authorBook);
            }
            
            
        }
    }
}

Book_Store/Views/AuthorsBooks/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>
@model BLL.Dtos.AuthorsBooksDto;
@inject BLL.Interfaces.IBookService Book;
@inject BLL.Interfaces.IAutherService Author;

<form asp-controller="AuthorsBooks" asp-action="Create" method="post" >
    <div asp-validation-summary="All">

    </div>
    
    
   
    <div class="form-group">
        <label>Choose Book </label>
      
        <select id="BookList" asp-for="BookId" >

            <option value="">Select</option>
            @foreach (var item in await Book.GetBooksAsync())
            {
                <option value="@item.Id">@item.Name</option>
            }


          
        </select>
        <span asp-validation-for="BookId"></span>
        </div>

    <div class="form-group">
        <label>Choose Author </label>

        <select id="BookList" asp-for="AuthorId">

            <option value="">Select</option>
            @foreach (var item in await Author.GetAuthorsAsync())
            {
                <option value="@item.Id">@item.Name</option>
            }



        </select>
        <span asp-validation-for="BookId"></span>
    </div>


        <button class="btn btn-info" type="submit">Add</button>

      </form>

        

@section MicroSoftValidation {

    <script src="~/plugins//jquery-validation//jquery.validate.js"> </script>
    <script src="~/plugins/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Book_Store/Views/AuthorsBooks/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

@{
    ViewData["Title"] = "Index";
}
@model IEnumerable<BLL.Dtos.AuthorsBooksDto>;

@section DataTableCS {
    @*<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">

    <link href="~/plugins/jquery-datatable/skin/bootstrap/css/datatables.bootstrap.css" rel="stylesheet" />*@
    <link href="~/plugins/bootstrap-select/css/bootstrap-select.min.css" rel="stylesheet" />
    <link href="~/plugins/jquery-datatable/skin/bootstrap/css/datatables.bootstrap.min.css" rel="stylesheet" />
}
    <div class="" style="margin-bottom: 25px;">
    <a class="w-100 p-4" asp-controller="AuthorsBooks" asp-action="Create"><button class="btn btn-primary w-100">Add</button></a>
</div>
  
     <div class="table-responsive">




            <table class="table table-bordered table-striped table-hover js-basic-example dataTable" id="AuthorBookTableId">
                    <thead class="thead-dark">
                        <tr>


                            <th scope="col">Book Name</th>
                            <th scope="col">Book Category</th>
                            <th scope="col">Book Rateing</th>

                            <th scope="col">AuthorName</th>


                           
                        </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@item.Book.Name</th>
                            <td>@item.Book.Category.Name</td>
                            <td>@item.Book.Rating</td>
                            <td>@item.Author.Name</td>


                        </tr>
                    }


                </tbody>
            </table>



  
</div>

   



@section DataTableJS{
   @* <script src="~/plugins/jquery-datatable/jquery.datatables.js"></script>
    <script src="~/plugins/jquery-datatable/skin/bootstrap/js/datatables.bootstrap.js"></script>*@
   @* <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>*@
    <script src="~/plugins/jquery-datatable/jquery.datatables.js"></script>
    <script src="~/plugins/jquery-datatable/skin/bootstrap/js/datatables.bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#AuthorBookTableId').DataTable();
        });
    </script>
   
    
}