Book_Store/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace Book_Store.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
      
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;  
        }
        public async Task<IActionResult> Index()
        {
            var Roles = await _roleManager.Roles.ToListAsync();
           
            return View(Roles);
        }
        public async Task<IActionResult> Create()
        {
           
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            try
            { 
                if(role==null)
                    throw new Exception("Please Enter Role Name");
                else
                {
                    var result = await _roleManager.CreateAsync(role);
                    if (result.Succeeded)
                        return RedirectToAction("Index");
                    else
                    {
                        throw new Exception("Cannot Create This Role");
                    }
                }

            }catch (Exception ex)
            {
                throw new Exception(ex.Message);
                return View(role);
            }
           
        }
    }
}

Book_Store/Controllers/UsersRoleController.cs
/*using AspNetCore*/
using BAL.Models;
using BLL.Identity.Dtos;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Immutable;
using System.Security.AccessControl;

namespace Book_Store.Controllers
{
    public class UsersRoleController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UsersRoleController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public  async Task <IActionResult> Index()
        {
            var Users =  _userManager.Users.Select(usr => new UserRoleVm()
            {
                UserId = usr.Id,
                UserName = usr.UserName,
                UserRoles = _roleManager.Roles.Select(r => new CheckBox()
                {
                    Id = r.Id,
                    Name = r.Name,
                    IsSelected = _userManager.IsInRoleAsync(usr, r.Name).Result
                }).ToList()

            }).ToList();


            
            
            
            return View(Users);
        }
        public async Task<IActionResult> ManageRoles(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var userRoles = await _userManager.GetRolesAsync(user);
            var Roles = await _roleManager.Roles.ToListAsync();
            var Result = new UserRoleVm()
            {
                UserId = user.Id,
                UserName = user.Email,
                UserRoles = Roles.Select(r => new CheckBox()
                {
                    Id = r.Id,
                    Name = r.Name,
                    IsSelected = _userManager.IsInRoleAsync(user, r.Name).Result

                }).ToList()
            };
           





            return View(Result);
        }
        [HttpPost]
        public async Task<IActionResult> ManageRoles(UserRoleVm model)
        {
            var Result = model;

            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null)
                return NotFound();
            var userRoles =await  _userManager.GetRolesAsync(user);

            await _userManager.RemoveFromRolesAsync(user, userRoles);
            var SelectedRoles = model.UserRoles.Where(sr => sr.IsSelected==true).Select(sr => sr.Name).ToList();
           await _userManager.AddToRolesAsync(user, SelectedRoles);




            return RedirectToAction("Index");   
        }


    }
}

Book_Store/Views/UsersRole/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model IEnumerable<BLL.Identity.Dtos.UserRoleVm>;

<h2>Index</h2>
<div class="col-md-3">
    <a class="w-100" asp-controller="Role" asp-action="Create"><button class="btn btn-primary w-100">Add</button></a>
</div>

<table class="table">

    <tbody>


        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">User ID</th>

                    <th scope="col">Name</th>


                    <th scope="col">Update</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.UserId</th>
                        <td>@item.UserName</td>
@*                        <td>@item.UserRoles.Where(r=>r.IsSelected).Select(r=>r.Name.ToString()).ToArray().Join(",")</td>
*@
                        <td>@String.Join(",",@item.UserRoles.Where(r=>r.IsSelected).Select(r=>r.Name.ToString()))</td>

                        <td> <a asp-route-Id="@item.UserId" asp-controller="UsersRole" asp-action="ManageRoles"> <button class="btn btn-danger">Manager Roles</button> </a></td>
                    </tr>
                }


            </tbody>
        </table>



    </tbody>
</table>

Book_Store/Views/UsersRole/ManageRoles.cshtml
@{
    ViewData["Title"] = "AssignUserToRoles";
}
@model   BLL.Identity.Dtos.UserRoleVm
<h2>AssignUserToRoles</h2>

<table class="table">

    <tbody>


        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">@Model.UserName</th>
                   
                  
                   


                  
                </tr>
            </thead>
            <tbody>
              
                    
                        <form asp-controller="UsersRole" asp-action="ManageRoles">
                           <input type="hidden" asp-for="UserName" />
                           <input type="hidden" asp-for="UserId" />
                            
                        @for (int i=0; i<Model.UserRoles.Count;i++)
                        {
                    <tr>

                        <td>
                            <div class="form-group">
                                <input type="hidden" asp-for="@Model.UserRoles[i].Id">
                                <input type="hidden" asp-for="@Model.UserRoles[i].Name">
                                <input asp-for="@Model.UserRoles[i].IsSelected" class="form-check-input">
                                <label   asp-for="@Model.UserRoles[i].IsSelected" >@Model.UserRoles[i].Name"</label>
                            </div>
                                    @* <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="true" id="flexCheckDefault">
                        <label class="form-check-label" for="flexCheckDefault">
                        Default checkbox
                        </label>
                        </div>*@
                        </td>
                    </tr>

                        }
                    <tr>
                    <button type="submit" class="btn btn-info">Save</button>
                    </tr>
                        </form>
                      
                       

                   
                  
                        

                    </tr>
              


            </tbody>
        </table>



    </tbody>
</table>